#!/bin/bash

echo    '###############################################################'   >  requirements.txt
echo    '# THIS FILE IS AUTOMATICALLY GENERATED BY get_requirements.sh #'   >> requirements.txt
echo    '# EDIT PIPFILES AND RUN ./get_requirements.sh TO UPDATE       #'   >> requirements.txt
echo -e '###############################################################\n' >> requirements.txt

pipenv lock -r >> requirements.txt
