name: rgbd
version: git
summary: colour light
description: >
  rgbd is a led light which can glow upto 7 colours . we are using it to turn automatically without human interaction .

grade: devel
confinement: devmode

parts:
  rgb:
    plugin: python
    python-version: python2
    source: .
    
apps:
  rgb:
    command: bin/rgb
