name: rgbd
version: master
summary: colour light
description: >
  rgbd is a led light which can glow upto 7 colours . we are using it to turn automatically without human interaction .

grade: devel
confinement: strict

parts:
  rgb:
    plugin: python
    python-version: python2
    source: .
    requirements: requirements.txt
    install: rm requirements.txt && ls -al
apps:
  rgb:
    command: rgb
